channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - gdal=3.10.2
  - numpy=2.2.6
  - scipy=1.16.0
  - pandas=2.3.1
  - joblib=1.4.2
  - shapely=2.1.1
  - pytest=8.3.3
  - pyproj=3.7.0
  - pillow=11.2.1
  - geopandas=1.1.1
  - networkx=3.5
  - pyarrow=21.0.0
  #- opencv=4.11
  - rtree=1.4.0
  - matplotlib=3.10.5
  - contextily=1.6.2
  - pip
  - pip:
    - loguru==0.7.2
    - pydantic==2.9.2
    - fiftyone==1.0.1
    - exif==1.6.0
    - "rasterio>=1.4.2,<1.6"
    - piq==0.8.0
    - matplotlib_scalebar==0.9.0
    - adjustText==1.3.0
    - matplotlib-map-utils==3.0.0
    - rioxarray==0.19.0
    - pycocotools==2.0.9
    - opencv-contrib-python==4.11.0.86
    - albumentations==1.0.3
    - tqdm==4.67.1
    - seaborn==0.13.2
    - wandb==0.20.1
    - timm==1.0.19